spring.application.name=suividoctorat
# mysql Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/doctoratdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=springuser
spring.datasource.password=spring123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# File Upload Configuration
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Thymeleaf - No cache
spring.thymeleaf.cache=false

server.servlet.session.timeout=30m
server.servlet.session.tracking-modes=cookie

# Multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
#email config - fake smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/

spring.security.user.name=user
spring.security.user.password=user
spring.security.user.roles=USER